language: go
go:
  - 1.7
  - 1.8
  - 1.9
  - '1.10'
  - tip
sudo: false

install:
  - go get golang.org/x/lint/golint

script:
  - golint $(go list ./... | grep -v /examples/)
  - go vet $(go list ./... | grep -v /examples/)
  - go test -v ./...
